on:
  push:
    branches:
      - test





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'print contents before'
        run: ls
   
      - uses: actions/checkout@v3
      
      - name: 'print contents after'
        run: ls      