on:
  push:
    branches:
      - test





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'test action'
        run: pwd

      - name: 'test printing'
        run: echo welcome  
  